[package]
name = "kubox"
version = "0.0.1"
authors = ["Luca Bruno <luca.bruno@coreos.com>"]

[dependencies]
envoption = "0.2"
error-chain = { version = "0.12", default-features = false }
nix = "0.16"

[profile.release]
lto = true
