[package]
name = "kubox"
version = "0.0.1"
authors = ["Luca Bruno <luca.bruno@coreos.com>"]

[dependencies]
envoption = "0.2"
error-chain = { version = "0.11", default-features = false }
nix = { git = "https://github.com/nix-rust/nix", rev = "63ce242" }

[profile.release]
lto = true
