apiVersion: v1
kind: Pod
metadata:
  name: kubox-bins-am64
spec:
  hostPID: true
  containers:
  - name: kubox-bins-amd64
    securityContext:
      privileged: true
    image: lucab/kubox-bins-amd64:dev-latest
    imagePullPolicy: Always
    command:
    - "/kubox"
